# Form implementation generated from reading ui file 'ui_files/main_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(230, 111)
        self.btn_setup = QtWidgets.QPushButton(parent=Dialog)
        self.btn_setup.setGeometry(QtCore.QRect(20, 70, 91, 23))
        self.btn_setup.setObjectName("btn_setup")
        self.btn_set_wallpaper = QtWidgets.QPushButton(parent=Dialog)
        self.btn_set_wallpaper.setEnabled(False)
        self.btn_set_wallpaper.setGeometry(QtCore.QRect(120, 70, 91, 23))
        self.btn_set_wallpaper.setObjectName("btn_set_wallpaper")
        self.label_info = QtWidgets.QLabel(parent=Dialog)
        self.label_info.setGeometry(QtCore.QRect(20, 10, 191, 41))
        self.label_info.setObjectName("label_info")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_setup.setText(_translate("Dialog", "setup"))
        self.btn_set_wallpaper.setText(_translate("Dialog", "set wallapper"))
        self.label_info.setText(_translate("Dialog", "click setup to begin configuration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
